# Generated by Django 6.0.2 on 2026-03-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0004_alter_adminlogin_admintype'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminlogin',
            name='Status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='DeptNo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Bill',
            field=models.CharField(max_length=500),
        ),
    ]
