# Generated by Django 6.0.2 on 2026-03-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0005_adminlogin_status_alter_department_deptno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
