# Generated by Django 6.0.2 on 2026-03-11 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HclsWebApi', '0006_checklogin'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklogin',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='checklogin',
            name='username',
            field=models.CharField(default=10, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='checklogin',
            table='CheckLogin',
        ),
    ]
